[tool.poetry]
name = "wewe"
version = "0.1.0"
description = ""
authors = ["Mr. Pesty"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pest = "^0.1.0"
uvicorn = "^0.25.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
