version: '3'

silent: false

tasks:
  default:
    desc: run pest command
    cmds:
      - poetry run pest
    silent: true

  fmt:check:
    aliases: [fmt]
    desc: check code format issues
    cmds:
      - poetry run black --check .

  fmt:fix:
    desc: fix code format issues
    cmds:
      - poetry run black . 

  lint:check:
    aliases: [lint]
    desc: check code lint issues
    cmds:
      - poetry run ruff check .

  lint:fix:
    desc: fix code lint issues
    cmds:
      - poetry run ruff check . --fix

  test:3.8:
    desc: 🧪 run tests on python 3.8
    cmds:
      - nox --session tests-3.8 --reuse-existing-virtualenvs

  test:3.9:
    desc: 🧪 run tests on python 3.9
    cmds:
      - nox --session tests-3.9 --reuse-existing-virtualenvs

  test:3.10:
    desc: 🧪 run tests on python 3.10
    cmds:
      - nox --session tests-3.10 --reuse-existing-virtualenvs
  
  test:3.11:
    desc: 🧪 run tests on python 3.11
    cmds:
      - nox --session tests-3.11 --reuse-existing-virtualenvs
  
  test:3.12:
    desc: 🧪 run tests on python 3.12
    cmds:
      - nox --session tests-3.12 --reuse-existing-virtualenvs

  test:all:
    desc: 🧪 run tests on all python versions
    cmds:
      - task --parallel test:3.12 test:3.11 test:3.10 test:3.9 test:3.8
