version: '3'

silent: false

tasks:
  default:
    desc: run pest command
    cmds:
      - poetry run pest
    silent: true

  fmt:check:
    aliases: [fmt]
    desc: check code format issues
    cmds:
      - poetry run black --check .

  fmt:fix:
    desc: fix code format issues
    cmds:
      - poetry run black . 

  lint:check:
    aliases: [lint]
    desc: check code lint issues
    cmds:
      - poetry run ruff check .

  lint:fix:
    desc: fix code lint issues
    cmds:
      - poetry run ruff check . --fix

  test:
    aliases: [t]
    desc: 🧪 run tests 
    cmds:
      - poetry run pytest
